// For adding custom fonts with other frameworks, see:
// https://tailwindcss.com/docs/font-family
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/header/header";

const fontSans = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  verification: {
    google: "fgKcEh2ocs8zJRcyH-yaqwa0jUsXLpDk5LM5_qVOMfc",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* <Header /> */}
      <body className={`${fontSans.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}




// import { Geist, Poppins } from "next/font/google";
// import "./globals.css";
// import { Toaster } from "@/components/ui/sonner";
// // import CalendlyBadge from '@/components/common/CalendlyBadge'
// // import TawkToWidget from "@/components/common/TawkToWidget";
// // import { ThemeProvider } from "@/components/ThemeProvider";
// // import ContactIcons from "@/components/ContactIcons";
// // import BigSavingsModal from "@/components/modals/big-savings-modal";
// // import { Suspense } from "react";
// // import GoogleAnalytics from "@/components/GoogleAnalytics";
// // import GoogleTagManager from "@/components/GoogleTagManager";
// // import TrackingInitializer from "@/components/TrackingInitializer";


// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
//   display: "swap",
//   preload: true,
// });

// const poppins = Poppins({
//   weight: ["400", "500", "600"],
//   subsets: ["latin"],
//   variable: "--font-poppins",
//   display: "swap",
//   preload: true,
// });

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       {/* <Suspense fallback={null}>
//         <GoogleAnalytics />
//         <GoogleTagManager />
//       </Suspense> */}
//       <body className={`${geistSans.variable} ${poppins.variable} antialiased`}>
//         {/* Google Tag Manager (noscript) */}
//         {/* <noscript>
//           <iframe
//             src="https://www.googletagmanager.com/ns.html?id=GTM-MRDR9686"
//             height="0"
//             width="0"
//             style={{ display: "none", visibility: "hidden" }}
//           />
//         </noscript> */}
//         {/* <ThemeProvider
//           attribute="class"
//           defaultTheme="light"
//           enableSystem={false}
//           disableTransitionOnChange
//         > */}
//           {/* <TrackingInitializer /> */}
//           {children}
//           <Toaster richColors position="top-center" />
//           {/* <BigSavingsModal /> */}
//           {/* <ContactIcons /> */}
//           {/* <CalendlyBadge /> */}
//           {/* <TawkToWidget /> */}
//         {/* </ThemeProvider> */}
//       </body>
//     </html>
//   );
// }



